# Generated by Django 4.2.1 on 2023-12-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='theread',
            new_name='thread',
        ),
    ]
