# Generated by Django 4.2.1 on 2023-12-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_username_of_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username_of_likes',
        ),
    ]
