# Generated by Django 4.2.1 on 2023-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name_of_likes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
