# Generated by Django 4.2.1 on 2023-12-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_name_of_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name_of_likes',
        ),
    ]
