# Generated by Django 4.2.1 on 2023-12-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_followers_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='Follower',
            new_name='follower',
        ),
    ]
