# Generated by Django 4.2.1 on 2023-12-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_post_comments_commentpost_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentPost',
        ),
    ]
