# Generated by Django 4.2.1 on 2023-12-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_delete_commentpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
